apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentelemetry
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opentelemetry
  template:
    metadata:
      labels:
        app: opentelemetry
    spec:
      containers:
        - name: opentelemetry
          image: otel/opentelemetry-collector-contrib:latest
          ports:
            - containerPort: 4317
---
apiVersion: v1
kind: Service
metadata:
  name: opentelemetry
  namespace: monitoring
spec:
  selector:
    app: opentelemetry
  ports:
    - protocol: TCP
      port: 4317
      targetPort: 4317
